---
title: "dimensional clustering test"
author: "Justin Lin"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(ggplot2)
library(dplyr)
library(MASS)
library(Rtsne)

source("Algorithms/dimensional clustering.R")
```

```{r}
Z = rbind(mvrnorm(n=50, mu=c(0,0,0,0,0,0,0,0,0,0), Sigma=diag(rep(1,10))),
          mvrnorm(n=60, mu=c(0,-5,0,0,0,0,0,0,0,0), Sigma=diag(rep(1,10))),
          mvrnorm(n=80, mu=c(0,0,3,0,0,0,0,0,0,0), Sigma=diag(rep(1,10))),
          mvrnorm(n=70, mu=c(0,0,0,6,0,0,0,0,0,0), Sigma=diag(rep(1,10))),
          mvrnorm(n=60, mu=c(0,0,0,0,-8,0,0,0,0,0), Sigma=diag(rep(1,10))))

real_labels = c(rep(1,50), rep(2, 60), rep(3, 80), rep(4, 70), rep(5, 60))

pca = prcomp(Z, center=TRUE)

tsne = Rtsne(Z, theta=0, perplexity = 30)
```

```{r, fig.height=10}
labels = dimensional_clustering(X=Z, cutoff=c(0.6, 0.5, 0.4, rep(0.3, 7)), scale=FALSE)

vertex_labels = labels
  for (i in 2:nrow(labels)) {
    vertex_labels[i,] = labels[i,] + max(vertex_labels[1:(i-1),])
  }

plot_graph(labels)
```


```{r}
df = data.frame(pca_x=pca$x[,1], pca_y=pca$x[,2],
                tsne_x=tsne$Y[,1], tsne_y=tsne$Y[,2],
                real_labels=real_labels, labels=vertex_labels[5,])
```

```{r}
ggplot(data=df, aes(x=pca_x, y=pca_y, color=factor(real_labels))) + geom_point()
ggplot(data=df, aes(x=pca_x, y=pca_y, color=factor(labels))) + geom_point()

ggplot(data=df, aes(x=tsne_x, y=tsne_y, color=factor(real_labels))) + geom_point()
ggplot(data=df, aes(x=tsne_x, y=tsne_y, color=factor(labels))) + geom_point()
```

```{r}
scores_list = list()
for (i in 2:10) {
  X = pca$x[,1:i]
  scores = vector()
  k = 2
  while (TRUE) {
    labels = kmeans(X, centers=k, nstart=50)$cluster
    si = silhouette(x=labels, dist=dist(X))
    scores = c(scores, summary(si)$avg.width)
    k = k + 1
    
    if (length(scores) >= 3 && scores[length(scores)] < scores[length(scores)-1] && scores[length(scores)-1] < scores[length(scores)-2]) {
      break
    }
  }
  scores_list = c(scores_list, list(scores))
}

scores_list
```

```{r}
data.frame(x=pca$x[,1],
           y=pca$x[,2],
           col=kmeans(pca$x[,1:2], centers=2, nstart=50)$cluster) %>%
  ggplot(aes(x=x, y=y, color=factor(col))) + geom_point()
```

