---
title: "DR tool experiments"
author: "Justin Lin"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(ggplot2)
library(igraph)
library(Rtsne)

source("Algorithms/DR assessment tool algs.R")
```

```{r}
n = 500
p = 10

X = rbind(matrix(rnorm(n*p/2, -10, 10), nrow = n/2, ncol = p),
          matrix(rnorm(n*p/2, 10, 10), nrow = n/2, ncol = p))
g = get_mst(X)
```

```{r}
num_paths = 7
path_num = weights = x = cluster = vector()

for (i in 1:num_paths) {
  points = sample(1:n, 2)
  path_weights = get_path_weights(get_shortest_path(g, points[1], points[2]))
  
  path_num = c(path_num, rep(i, length(path_weights)))
  weights = c(weights, path_weights)
  
  x = c(x, seq(from = 0, to = 10, length.out = length(path_weights)))
  
  same_cluster = ifelse(points[1] <= n/2 && points[2] > n/2 ||
                          points[2] <= n/2 && points[1] > n/2,
                        "Different Cluster", "Same Cluster")
  
  cluster = c(cluster, rep(same_cluster, length(path_weights)))
}

df = data.frame(path_num = path_num, weights = weights, x = x, cluster = cluster)
```


```{r}
ggplot(df, aes(x = x, y = weights, color = factor(path_num))) + 
  geom_point() + 
  geom_line(aes(linetype = cluster)) + 
  labs(y = "Weight", linetype = "Cluster", color = "Path Number") + 
  theme(axis.title.x = element_blank(),
        axis.text.x = element_blank(),
        axis.ticks.x = element_blank())
```

```{r}
Y = Rtsne(X, dims = 2, perplexity = 30)$Y

plot_path(Y, 1, 350)
```


