---
title: "high dim clusters dim cluster"
author: "Justin Lin"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(ggplot2)
library(dplyr)
library(MASS)
library(Rtsne)
library(dslabs)

source("Algorithms/dimensional clustering.R")
```


```{r}
Y = rbind(mvrnorm(n=30, mu=runif(n=10, min=-5, max=10), Sigma=diag(abs(rnorm(n=10, mean=0, sd=10)))),
          mvrnorm(n=20, mu=runif(n=10, min=-5, max=10), Sigma=diag(abs(rnorm(n=10, mean=0, sd=10)))),
          mvrnorm(n=50, mu=runif(n=10, min=-5, max=10), Sigma=diag(abs(rnorm(n=10, mean=0, sd=10)))),
          mvrnorm(n=40, mu=runif(n=10, min=-5, max=10), Sigma=diag(abs(rnorm(n=10, mean=0, sd=10)))),
          mvrnorm(n=25, mu=runif(n=10, min=-5, max=10), Sigma=diag(abs(rnorm(n=10, mean=0, sd=10)))),
          mvrnorm(n=30, mu=runif(n=10, min=-5, max=10), Sigma=diag(abs(rnorm(n=10, mean=0, sd=10)))),
          mvrnorm(n=15, mu=runif(n=10, min=-5, max=10), Sigma=diag(abs(rnorm(n=10, mean=0, sd=10)))))

Z = cbind(Y, matrix(0, ncol=50, nrow=210)) + mvrnorm(n=210, mu=rep(0,60), Sigma=diag(rep(5,60)))

real_labels = rep(1:7, c(30, 20, 50, 40, 25, 30, 15))
pca = prcomp(Z, center=TRUE)

tsne = Rtsne(Z, theta=0, perplexity = 30)
```


```{r, fig.height=10}
labels = dimensional_clustering(X=Z, cutoff=c(0.7, 0.6, 0.5, rep(0.4, 3), rep(0.3, 54)), scale=FALSE)

vertex_labels = labels
  for (i in 2:nrow(labels)) {
    vertex_labels[i,] = labels[i,] + max(vertex_labels[1:(i-1),])
  }

plot_graph(labels)
```

```{r}
scores_list = list()
for (i in 2:10) {
  X = pca$x[,1:i]
  scores = vector()
  k = 2
  while (TRUE) {
    labels = kmeans(X, centers=k, iter.max=100, nstart=50)$cluster
    si = silhouette(x=labels, dist=dist(X))
    scores = c(scores, summary(si)$avg.width)
    k = k + 1
    
    if (length(scores) >= 3 && scores[length(scores)] < scores[length(scores)-1] && scores[length(scores)-1] < scores[length(scores)-2]) {
      break
    }
  }
  scores_list = c(scores_list, list(scores))
}

scores_list
```


```{r}
df = data.frame(pca_x=pca$x[,1], pca_y=pca$x[,2],
                tsne_x=tsne$Y[,1], tsne_y=tsne$Y[,2],
                real_labels=real_labels, labels=vertex_labels[5,], k_means_labels = kmeans(Z, centers=7, nstart=50)$cluster)
```

```{r}
ggplot(data=df, aes(x=pca_x, y=pca_y, color=factor(real_labels))) + geom_point()
ggplot(data=df, aes(x=pca_x, y=pca_y, color=factor(labels))) + geom_point()
ggplot(data=df, aes(x=pca_x, y=pca_y, color=factor(k_means_labels))) + geom_point()

ggplot(data=df, aes(x=tsne_x, y=tsne_y, color=factor(real_labels))) + geom_point()
ggplot(data=df, aes(x=tsne_x, y=tsne_y, color=factor(labels))) + geom_point()
ggplot(data=df, aes(x=tsne_x, y=tsne_y, color=factor(k_means_labels))) + geom_point()
```