---
title: "MNIST experiments"
author: "Justin Lin"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(ggplot2)
library(igraph)
library(Rtsne)
library(dslabs)
library(dplyr)
library(plotly)

source("Algorithms/DR assessment tool algs.R")
```

```{r}
n = 3000
p = 300
k = 30

data = read_mnist()$train
subsample = sample(1:60000, n)

Z = data$images[subsample,]
labels = data$labels[subsample]

Z_pca = prcomp(Z, rank. = p)$x
Z_mst = get_mst(Z_pca)
Z_nng = get_nng(Z_pca, k = k)
Z_sl = get_avg_linkage_graph(Z_pca)

X = Rtsne(Z, dims = 2, perplexity = 30)$Y
```

```{r}
df_long = data.frame(x = X[,1], y = X[,2], labels = labels, id = subsample)

p1 =  ggplot(df_long, aes(x = x, y = y, color = factor(labels), label = id)) +
  geom_point(size = 1) +
  labs(color = "Digit")

ggplotly(p1, tooltip = c("x", "y", "label"))
```


```{r}
ggplotly(add_path(p1, df_long, get_shortest_path(g, 1, 2)),
         tooltip = c("x", "y", "label"))
```

```{r}
save(Z_pca, Z_mst, Z_nng, Z_sl, X, df_long, labels, data, file = "Data/MNIST data.Rda")
```

