---
title: "MST Stability"
author: "Justin Lin"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(MASS)
library(ade4)
library(ggplot2)

source("../Final/DR tool functions final.R")
```

```{r}
Z = rbind(mvrnorm(n=50, mu=c(10,0,0,0,0), Sigma=diag(abs(rnorm(n=5, mean=0, sd=5)))),
          mvrnorm(n=50, mu=c(0,-10,0,0,0), Sigma=diag(abs(rnorm(n=5, mean=0, sd=5)))),
          mvrnorm(n=50, mu=c(0,0,5,0,0), Sigma=diag(abs(rnorm(n=5, mean=0, sd=5)))),
          mvrnorm(n=50, mu=c(0,0,0,8,0), Sigma=diag(abs(rnorm(n=5, mean=0, sd=5)))),
          mvrnorm(n=50, mu=c(0,0,0,-8,0), Sigma=diag(abs(rnorm(n=5, mean=0, sd=5)))),
          mvrnorm(n=50, mu=c(0,0,0,0,4), Sigma=diag(abs(rnorm(n=5, mean=0, sd=5)))),
          mvrnorm(n=50, mu=c(0,0,0,0,-6), Sigma=diag(abs(rnorm(n=5, mean=0, sd=5)))))

Z = cbind(Z, matrix(0, nrow=nrow(Z), ncol=25))

Z_dist = dist(Z)
mst_orig = get_mst(Z_dist)
graph_dist_orig = distances(mst_orig)
```

```{r}
b = 50

correlations = vector(length=b)
euclidean_correlations = vector(length=b)

shep = vector(length=b)
euclidean_shep = vector(length=b)

for (i in 1:b) {
  noise = mvrnorm(nrow(Z), mu=rep(0, ncol(Z)), Sigma=diag(rep(2, ncol(Z))))
  Z_noise = Z + noise
  Z_noise_dist = dist(Z_noise)
  
  dist_mat = dist(Z_noise)
  
  mst = get_mst(dist_mat)
  
  graph_dist = distances(mst)
  
  correlations[i] = mantel.rtest(as.dist(graph_dist_orig), as.dist(graph_dist))$obs
  euclidean_correlations[i] = mantel.rtest(Z_noise_dist, Z_dist)$obs
  
  shep[i] = cor(as.dist(graph_dist_orig), as.dist(graph_dist), method="spearman")
  euclidean_shep[i] = cor(Z_noise_dist, Z_dist, method="spearman")
}
```

```{r}
df = data.frame(cor = c(euclidean_correlations, correlations),
                shep = c(euclidean_shep, shep),
                type  =c(rep("Euclidean", b), rep("MST", b)))

ggplot(df, aes(x=cor, y=type, color=type)) +
  geom_boxplot() +
  xlim(-1,1)

ggplot(df, aes(x=shep, y=type, color=type)) +
  geom_boxplot() +
  xlim(-1,1)
```

