---
title: "R vs. Python Tree Tests"
author: "Justin Lin"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(MASS)

source("../Final/DR tool functions final.r")
source("mst tools.R")
```

```{r}
library(reticulate)

use_python("/opt/anaconda3/envs/spyder_env/bin/python")
py_config()
py_available()
```

```{r}
Z = rbind(mvrnorm(n=40, mu=c(10,0,0,0,0), Sigma=diag(abs(rnorm(n=5, mean=0, sd=5)))),
          mvrnorm(n=200, mu=c(0,-10,0,0,0), Sigma=diag(abs(rnorm(n=5, mean=0, sd=5)))),
          mvrnorm(n=100, mu=c(0,0,5,0,0), Sigma=diag(abs(rnorm(n=5, mean=0, sd=5)))),
          mvrnorm(n=80, mu=c(0,0,0,8,0), Sigma=diag(abs(rnorm(n=5, mean=0, sd=5)))),
          mvrnorm(n=30, mu=c(0,0,0,-8,0), Sigma=diag(abs(rnorm(n=5, mean=0, sd=5)))),
          mvrnorm(n=60, mu=c(0,0,0,0,4), Sigma=diag(abs(rnorm(n=5, mean=0, sd=5)))),
          mvrnorm(n=130, mu=c(0,0,0,0,-6), Sigma=diag(abs(rnorm(n=5, mean=0, sd=5)))))
Z_dist = dist(Z)
cluster = rep(1:7, c(40, 200, 100, 80, 30, 60, 130))

og_mst = get_mst(Z_dist)
og_tree = get_simple_medoid_mst(Z_dist, og_mst, cluster)
```

```{r}
b = 30
mat_list = list()
for (i in 1:30) {
  mat_list[[i]] = Z + mvrnorm(nrow(Z), mu=rep(0, ncol(Z)), Sigma=diag(rep(2, ncol(Z))))
}
```

```{r}
dists = vector(length=b)

for (i in 1:b) {
  Z_noise = mat_list[[i]]
  Z_noise_dist = dist(Z_noise)
  
  mst = get_mst(Z_noise_dist)
  tree = get_simple_medoid_mst(Z_noise_dist, mst, cluster)
  
  dists[i] = RF_dist(og_tree, tree)
}
```

```{python}
import numpy as np
import igraph as ig
import networkx as nx
from scipy.spatial import distance_matrix

import sys
sys.path.append('Python experiments/')
import mst_tools

Z = r.Z
Z_dist = distance_matrix(Z, Z)
cluster = r.cluster
                          
og_mst = mst_tools.get_mst(Z_dist)
og_tree = mst_tools.get_simple_medoid_mst(Z_dist, og_mst, cluster)
og_network = og_tree.to_networkx()

b = int(r.b)
dists_py = np.empty(b, dtype='int')

count = 0
for i in range(b):
    Z_noise = r.mat_list[i]
    Z_noise_dist = distance_matrix(Z_noise, Z_noise)
    
    mst = mst_tools.get_mst(Z_noise_dist)
    tree = mst_tools.get_simple_medoid_mst(Z_noise_dist, mst, cluster)
    network = tree.to_networkx()
    
    dists_py[count] = nx.graph_edit_distance(og_network,
                                             network, 
                                             node_match=mst_tools.return_eq)
    
    count += 1
```

```{r}
plot(dists, py$dists_py)
cor(dists, py$dists_py)
```