---
title: "PCA Path Experiments"
author: "Justin Lin"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(ggplot2)
library(dslabs)
library(umap)
library(dplyr)

source("../Final/DR tool final.R")
source("../Final/DR tool functions final.R")
source("print mst.R")
```

```{r}
library(reticulate)
use_python("/opt/anaconda3/envs/skenv/bin/python")
py_config()
py_available()
```

```{r}
set.seed(2618)

n = 2000
p = 300

data = read_mnist()$train
subsample = sample(1:nrow(data$images), n)

Z = data$images[subsample,]
real_labels = data$labels[subsample]

id = subsample
Z_pca = unname(prcomp(Z, rank. = p)$x)

Z_dist = dist(Z_pca, method="manhattan")
X = umap(Z_pca, method="umap-learn", n_neighbors=30)$layout

kmeans_cluster = kmeans(Z_pca, centers=10, iter.max=100, nstart=20)$cluster

tree = get_mst(Z_dist)
```

```{r}
keep = kmeans_cluster %in% c(1,2)

Z1 = Z[keep,]
Z1_pca = unname(prcomp(Z1, rank. = p)$x)
X1 = umap(Z1_pca, method="umap-learn", n_neighbors=30)$layout

id1 = id[keep]
cluster1 = kmeans_cluster[keep]

sp = get_shortest_path(tree, which(id == 51188), which(id == 53349))

path_ids = as.numeric(sp$vpath)
path_pts = Z_pca[path_ids,]

# run_app(Z1, X1, cluster1, id1)
```

```{r}
b = 30

for (i in 1:b) {
  u = matrix(rnorm(p), ncol=1)
  u = u/norm(u, type='2')

  v = matrix(rnorm(p), ncol=1)
  v = v/norm(v, type='2')

  w = v - as.numeric(t(v) %*% v) * u

  R = matrix(c(v,w), ncol=2)
  
  X_rot = Z1_pca %*% R
  
  df_rot = data.frame(x=X_rot[,1], y=X_rot[,2], cluster=cluster1)
  
  df_path = data.frame(x=X_rot[match(path_ids, which(keep)),1],
                       y=X_rot[match(path_ids, which(keep)),2])
  
  print(ggplot(df_rot, aes(x=x, y=y)) +
    geom_point() +
    scale_color_viridis_c() +
    geom_segment(data=df_path,
               aes(xend=lead(x), yend=lead(y)),
               linewidth=0.3))
}
```